[Queens-only] Fix redis pull error on tls-e
Now that paunch does a docker pull all the time in queens
(https://review.opendev.org/#/c/753082/), we need to
use the non-pcmk image. Otherwise we error out with:

  Error: image rh-osbs/rhosp13-openstack-redis:pcmklatest not found

Reported-By: Luca Miccini <lmiccini@redhat.com>
Co-Authored-By: Damien Ciabrini <dciabrin@redhat.com>

Change-Id: I62d8790a8ec46128c0d74bad4debb0d03d05c835