Fix the Octavia amphora provider driver description
octavia_tempest_plugin.tests.api.v2.test_provider.ProviderAPITest.test_provider_list
fails with the following:

testtools.matchers._impl.MismatchError: 'The Octavia Amphora driver.' != 'Octavia Amphora Driver.'

Change-Id: I37245f6cada11f060b8a0b8da06a583d64bb347b
(cherry picked from commit 88d6c029db2aa0d7ae8106f7add5d88b8562e61b)
(cherry picked from commit b701f9110b19643376ea0e29d90f78a0486fcb63)