Fixup ipaclient.yaml for python3
This change does two things:
1. it uses print() which is the only supported way of calling print
   in python3 (and still works with python2). This way we avoid the
   following error:

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('...')?

2. It uses the PythonInterpreter variable to choose the python
   interpreter

Tested and we correctly get the right wanted interpreter:
...
fqdn=`echo $data | /usr/bin/python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj.get("join", {}).get("hostname", ""))'`
...

Change-Id: I6e68664c650d0481a9f0cfd21985434d8c75e1a2
Co-Authored-By: Luca Miccini <lmiccini@redhat.com>