[Train-only] Remove redis_tls_proxy if at step2
When we move redis_tls_proxy from step2 to step1 (which is the correct
thing to do) via https://review.opendev.org/c/openstack/tripleo-heat-templates/+/777549:
"""
We also move the redis_tls_proxy from step_2/start_order: 3 to step_1
since it actually makes sense to have it run before we start the
redis pcmk bundle at step 2 (i.e. so the slave replica can work right
away from the start).
"""

The problem is that paunch by design does not manage containers moving from stepX to
stepX-1 and so during a minor update, it will create redis_tls_proxy
at step1 but since the previous container has tripleo_config=step2 label
it won't detect that it has to remove it and recreate and it will fail
with:
podman create --name redis_tls_proxy --label config_id=tripleo_step1 --label container_name=redis_tls_proxy

....

Error: error creating container storage: the container name \"redis_tls_proxy\" is already in use by \"556f965b47b044fa48ef8194f2cf0adaad46e8145f1e4afdb0af4d70977ad561\". You have to remove that container to be able to reuse that name.: that name is already in use\

Tested by running at 16.1 -> 16.2 update and we correctly get past this
error and redis is fully up and running.

We need this only in Train as a fresh deployment or ffu is not affected.

Closes-Bug: #1931145
Change-Id: I9bea643511f90167ca7b9f0285c1eaf8211d6e7d