Move permissions from neutron to ovn-bgp
The ovn-bgp-agent user was moved from neutron to ovn-bgp
at [1]. Changing the permissions in the tht side to avoid:

KeyError: "getpwnam(): name not found: 'neutron'"

[1] https://review.opendev.org/c/openstack/tripleo-common/+/833604

Change-Id: I62950490bafa50f372c6a1f22b8e8a88301310c4