Allow stacks to remove old update resources
Change I6c5eafe76eb53bc38d100a9ba132dd8fe6dd2d5f removed old
update-related resources, but it seems that we need to do such removal
in two steps to allow smooth transition for existing stacks: first
remove them from the stack, and only then completely remove the
mapping from resource registry. If we try to do both at the same time,
we get:

ERROR: The Resource Type (OS::TripleO::Tasks::UpdateWorkflow) could
not be found.

So we'll need to keep these resource registry entries around (even
though mapped to OS::Heat::None) for the Rocky cycle still. They can
be removed in S.

Change-Id: I866e659bd373dfb2816508165b7f3abb9580e2d0
Closes-Bug: #1758014