Fix Neutron enable_*_agent* Hiera parameters
This change will fix a logic error when L3 agent was disabled, where
a Pacemaker constraint (neutron-dhcp-agent-to-l3-agent-constraint) were
still looking for l3_agent_service in the Puppet catalog, but could not
because L3 agent was disabled.
It was sending this Puppet error:
Error: Could not find dependency
Pacemaker::Resource::Service[neutron-l3-agent] for
Pacemaker::Constraint::Base[neutron-dhcp-agent-to-l3-agent-constraint]

Closes-Bug: 1583988
Change-Id: I0e5d24d844810c58a3205303399d1c20773af3dd
(cherry picked from commit 887f35b0f1fcc2218636564948f36170ed077934)