Fix ironic containers data owning races
Complements I5ad4956174346f0$24945852da09f3841c3378c2b.
Fix ironic_pxe/inspector containers missing the kolla_config sections
to recursively chown /var/lib/ironic* shared paths. That removes data
owning races across other ironic containers starting on earlier or the
same steps/order.

For example, when ironic_pxe_http fails to access the
/var/lib/ironic/httpboot path shared with ironic_conductor, the latter
reports errors like:

DriverLoadError: Driver, hardware type or interface ilo-pxe could not
be loaded. Reason: [Errno 13] Permission denied:
'/var/lib/ironic/httpboot/...

Fixing the dir owner allows HW provisioning to complete w/o such
errors.

Change-Id: I34b54077c1c610a4bed73129e9784b2fa353e944
Closes-bug: #1783762