fix generate_environments to run in python3
This patch fix the following error when running python3
TypeError: can only concatenate list (not "dict_keys") to list

Change-Id: Ic487bf4c4f6cb2bc35011416056bef1417a23076
(cherry picked from commit 609784ded1e298c3120defb0330d890763ba54f6)