[Mitaka only] Install packages for new components on upgrade
AODH is already installed at the point of controller upgrade script
running, because it has a separate migration step, but Sahara and
Gnocchi aren't installed yet, and it leads to errors during the converge
step:

Error: /Stage[main]/Sahara::Db::Sync/Exec[sahara-dbmanage]: Could not find command 'sahara-db-manage'
Error: /Stage[main]/Gnocchi::Db::Sync/Exec[gnocchi-db-sync]: Could not find command 'gnocchi-upgrade'

Installing those packages makes the converge finish fine.

Change-Id: Iaad51f37c59f8f46436bbb200d469e24457176ed
Closes-Bug: #1597674