Comment out the empty "parameter_defaults"
If an operator passes this file and gets their actual RHSM data in
another environment file, such as:
openstack overcloud deploy \
  -e /usr/share/openstack-tripleo-heat-templates/environments/rhsm.yaml \
  -e /home/stack/custom-rhsm.yaml

it will fail with the following error:
ValueError: environment has empty section "parameter_defaults"

Commenting out the empty parameter_defaults will avoid this kind of
issue - while allowing the operator to still pass their files.

Change-Id: I4d0fef3fe2f821ad694858b0bf109b555f736823
(cherry picked from commit 226d5cb2a60b27fddb0995fa89ac1e2a0f1db5d8)