Remove double slashes in path
In some containers we have double slashes in our paths. This has always
worked in podman 3.x but breaks with podman 4.x

* Working

[root@undercloud-0 step_1]# podman run -it --rm --net=host -v /etc/pki/tls/private/overcloud_endpoint.pem:/var/lib/kolla/config_files/src-tls/etc/pki/tls/private/overcloud_endpoint.pem undercloud-0.ctlplane.home.arpa:8787/tripleo_centos9/openstack-haproxy:latest bash
[root@undercloud-0 /]# exit

Broken (see the '//' before src-tls)

[root@undercloud-0 step_1]# podman run -it --rm --net=host -v /etc/pki/tls/private/overcloud_endpoint.pem:/var/lib/kolla/config_files//src-tls/etc/pki/tls/private/overcloud_endpoint.pem undercloud-0.ctlplane.home.arpa:8787/tripleo_centos9/openstack-haproxy:latest bash
Error: OCI runtime error: mount `/etc/pki/tls/private/overcloud_endpoint.pem` to `/var/lib/kolla/config_files//src-tls/etc/pki/tls/private/overcloud_endpoint.pem`: Not a directory

Closes-Bug: #1949888
Change-Id: Ic7c3469c69841293902f29d5772be202978fac32