Don't try and clean non-existing nic config dir
tools/process-templates.py -c was failing with a traceback:
 FileNotFoundError: [Errno 2] No such file or directory:
 './network/config'

That directory was removed in commit
3c246d15d87921ae423f3f012304368b127ecfbe, so we can remove trying to
clean it from process-templates.py

Closes-Bug: #1907268
Change-Id: I9e07d82240dee7d066634b1cade1390fe62e8341
Signed-off-by: James Slagle <jslagle@redhat.com>