Fix Heat condition for RHEL registration yum update
There were 2 problems with this condition making the
rhel-registration.yal template broken:

"conditions" should be "condition"

The condition should refer to just a condition name defined in the
"conditions:" section of the template.

When Id84d156cd28413309981d5943242292a3a6fa807 was backported to ocata
and newton, it broke RHEL registration on those branches, and fails
with:

===
ERROR: Failed to validate: Failed to validate: resources[0]: Failed to
validate: resources.NodeExtraConfig: "conditions" is not a valid keyword
inside a resource definition'
===

I14d5c72cf86423808e81f1d8406098d5fd635e66 also needs to be backported to
resolve the issue.

Change-Id: I14d5c72cf86423808e81f1d8406098d5fd635e66
Closes-Bug: #1709916
(cherry picked from commit 589b18dafc5f9a79d39bfb0a1d8ecbc0d3d34627)